version: '2'
services:
  specialroutes-service:
    image: kaloyan84/tmx-specialroutes-service:chapter7
    ports:
      - "8910:8910"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8910"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        8761
      DATABASESERVER_PORT:      5432
      CONFIGSERVER_PORT:        8888
      ENCRYPT_KEY:       "IMSYMMETRIC"