version: '2'
services:
  zuulserver:
    image: kaloyan84/tmx-zuulsvr:chapter7
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"